// <auto-generated />
using System;
using Backend_sr1645.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Backend_sr1645.Migrations
{
    [DbContext(typeof(ShopContext))]
    [Migration("20241204164611_Data")]
    partial class Data
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.36")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Backend_sr1645.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float?>("Price")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "pomidor",
                            Price = 5.6f
                        },
                        new
                        {
                            Id = 2,
                            Name = "ziemniaki",
                            Price = 2.6f
                        },
                        new
                        {
                            Id = 3,
                            Name = "ogórek",
                            Price = 6.2f
                        },
                        new
                        {
                            Id = 4,
                            Name = "kalafior",
                            Price = 10.6f
                        },
                        new
                        {
                            Id = 5,
                            Name = "brokuł",
                            Price = 8.9f
                        },
                        new
                        {
                            Id = 6,
                            Name = "cukinia",
                            Price = 7.99f
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
